const CURRENT_WEATHER_PREFIX = 'CURRENT_WEATHER/';
const LOCATIONS_PREFIX = 'LOCATIONS/';

export const LOCATIONS_SET_LOCATIONS = `${LOCATIONS_PREFIX}SET_LOCATIONS`;
export const LOCATIONS_FAIL = `${LOCATIONS_PREFIX}FAIL`;
export const LOCATIONS_LOADING = `${LOCATIONS_PREFIX}LOADING`;
export const LOCATIONS_LOADED = `${LOCATIONS_PREFIX}LOADED`;

export const CURRENT_SET_CURRENT = `${CURRENT_WEATHER_PREFIX}SET_CURRENT`;
export const CURRENT_FAIL = `${CURRENT_WEATHER_PREFIX}FAIL`;
export const CURRENT_LOADING = `${CURRENT_WEATHER_PREFIX}LOADING`;
export const CURRENT_LOADED = `${CURRENT_WEATHER_PREFIX}LOADED`;
